# -*- mode: ruby -*-
# vi: set ft=ruby :

members = {
  # Name     num, CPU, RAM, IP_START 
  'etcd' => [ 1, 1, 1024, 11 ],
  'node' => [ 2, 1, 1024, 101 ],
}

PREFIX = "100.100.100"

Vagrant.configure("2") do |config|
  #define Linux Type
  config.vm.box = "centos/7"

  #all machines use the same key
  config.ssh.insert_key = false

  #Iterate memeber to set up predefined hosts
  members.each do |name, (count, cpu, ram, ipstart)|
    (1..count).each do |i|
      config.vm.define member = "%s-%02d" % [name, i] do |m|
        m.vm.hostname = member
        m.vm.provider :virtualbox do |v|
          v.name              = member
          v.cpus              = cpu
          v.memory            = ram
          v.check_guest_additions = false
          v.functional_vboxsf     = false
          #v.customize ["modifyvm", :member, "--natdnshostresolver1", "on"]
          #v.customize ["modifyvm", :id, "--memory", ram]
        end
        #Host IP
        ip = "%s.%02d" % [PREFIX, ipstart+i-1]
        m.vm.network :private_network, ip: ip

      end
    end
  end
end
